name: Create Webogram Docker Image
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      uses: actions/buildah-build@v3
      with:
        image: yanuar21/webogram
        tags: latest
        dockerfiles: |
          ./Dockerfile
          
    - name: push image to registry
      uses: actions/push-to-registry@v3
      with:
        image: ${{ steps.build-image.outputs.mage }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
