name: Create Webogram Docker Image
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      uses: actions/checkout@v3
      with:
        image: yanuar21/webogram
        tags: latest
        dockerfiles: |
          ./Dockerfile
          
    - name: list image
      run: docker images
      
